import fc from "fast-check";
import { describe, expect, it } from "vitest";
import type { ContentType, ScannedFile } from "../shared/types.ts";
import { buildContentGraph, deriveTitle, filePathToId } from "./contentGraph.ts";

/**
 * Property-based tests for ID generation and title derivation.
 *
 * Tests Properties 10 and 11 from the design document.
 */

/** Arbitrary for a simple filename stem (no dots, no slashes, no spaces). */
const arbStem = fc
  .stringMatching(/^[a-zA-Z][a-zA-Z0-9_-]*$/)
  .filter((s) => s.length >= 1 && s.length <= 30);

/** Arbitrary for a file extension. */
const arbExt = fc.constantFrom(".md", ".jpg", ".png", ".mp4", ".mp3");

/** Arbitrary for a valid YYYY-MM-DD date string. */
const arbDatePrefix = fc
  .record({
    year: fc.integer({ min: 1900, max: 2099 }),
    month: fc.integer({ min: 1, max: 12 }),
    day: fc.integer({ min: 1, max: 28 }),
  })
  .map(
    ({ year, month, day }) =>
      `${String(year).padStart(4, "0")}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`,
  );

/** Arbitrary for an optional directory prefix (no trailing slash for empty). */
const arbDirSegment = fc
  .stringMatching(/^[a-zA-Z][a-zA-Z0-9_-]*$/)
  .filter((s) => s.length >= 1 && s.length <= 20);

describe("Content Graph — Property 10: ID uniqueness and generation", () => {
  /**
   * For any set of files with distinct relative paths, filePathToId produces unique IDs.
   *
   * **Validates: Requirements 5.7, 12.1, 12.3**
   */
  it("produces unique IDs for distinct relative paths", () => {
    fc.assert(
      fc.property(
        fc.uniqueArray(
          fc
            .tuple(arbDirSegment, arbStem, arbExt)
            .map(([dir, stem, ext]) => `${dir}/${stem}${ext}`),
          {
            minLength: 2,
            maxLength: 20,
            comparator: (a, b) => filePathToId(a) === filePathToId(b),
          },
        ),
        (paths) => {
          const ids = paths.map((p) => filePathToId(p));
          const uniqueIds = new Set(ids);
          expect(uniqueIds.size).toBe(paths.length);
        },
      ),
      { numRuns: 300 },
    );
  });

  /**
   * The ID is generated by stripping the extension, replacing `/` with `--`,
   * replacing spaces with `-`, and lowercasing.
   *
   * **Validates: Requirements 5.7, 12.1, 12.3**
   */
  it("strips extension, replaces / with --, replaces spaces with -, and lowercases", () => {
    fc.assert(
      fc.property(arbStem, arbExt, (stem, ext) => {
        const relativePath = `${stem}${ext}`;
        const id = filePathToId(relativePath);

        // No extension in the ID
        expect(id).not.toContain(ext);
        // Lowercased
        expect(id).toBe(id.toLowerCase());
        // No slashes
        expect(id).not.toContain("/");
        // No spaces
        expect(id).not.toMatch(/\s/);
      }),
      { numRuns: 300 },
    );
  });

  /**
   * Path separators are replaced with `--` in the ID.
   *
   * **Validates: Requirements 5.7, 12.1**
   */
  it("replaces path separators with --", () => {
    fc.assert(
      fc.property(arbDirSegment, arbStem, arbExt, (dir, stem, ext) => {
        const relativePath = `${dir}/${stem}${ext}`;
        const id = filePathToId(relativePath);

        expect(id).toContain("--");
        expect(id).toBe(`${dir}--${stem}`.toLowerCase());
      }),
      { numRuns: 300 },
    );
  });

  /**
   * Spaces in filenames are replaced with `-`.
   *
   * **Validates: Requirements 5.7, 12.1**
   */
  it("replaces spaces with hyphens", () => {
    const id = filePathToId("2025-03-15 journal entry.md");
    expect(id).toBe("2025-03-15-journal-entry");
  });
});

describe("Content Graph — Property 11: Title derivation priority", () => {
  /**
   * For any file with a non-empty frontmatter.title, the derived title equals
   * that frontmatter value (trimmed).
   *
   * **Validates: Requirements 5.8, 12.2**
   */
  it("uses frontmatter.title when present and non-empty", () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }).filter((s) => s.trim().length > 0),
        arbStem,
        arbExt,
        (title, stem, ext) => {
          const relativePath = `${stem}${ext}`;
          const frontmatter = { title };
          const result = deriveTitle(relativePath, frontmatter);
          expect(result).toBe(title.trim());
        },
      ),
      { numRuns: 300 },
    );
  });

  /**
   * For any file without a frontmatter title, the derived title is the filename
   * with extension, date prefix, and separators stripped.
   *
   * **Validates: Requirements 5.8, 12.2**
   */
  it("derives title from filename when no frontmatter title exists", () => {
    fc.assert(
      fc.property(arbStem, arbExt, (stem, ext) => {
        const relativePath = `some-dir/${stem}${ext}`;
        const result = deriveTitle(relativePath, null);

        // Should not contain the extension
        expect(result).not.toContain(ext);
        // Should be non-empty
        expect(result.length).toBeGreaterThan(0);
      }),
      { numRuns: 300 },
    );
  });

  /**
   * Date prefixes are stripped from the filename when deriving the title.
   *
   * **Validates: Requirements 5.8, 12.2**
   */
  it("strips YYYY-MM-DD date prefix from filename", () => {
    fc.assert(
      fc.property(arbDatePrefix, arbStem, arbExt, (dateStr, stem, ext) => {
        const relativePath = `${dateStr}-${stem}${ext}`;
        const result = deriveTitle(relativePath, null);

        // The date prefix should not appear in the title
        expect(result).not.toMatch(/^\d{4}-\d{2}-\d{2}/);
      }),
      { numRuns: 300 },
    );
  });

  /**
   * Underscores and hyphens in the filename are replaced with spaces in the title.
   *
   * **Validates: Requirements 5.8, 12.2**
   */
  it("replaces underscores and hyphens with spaces", () => {
    const result = deriveTitle("my_cool-file.md", null);
    expect(result).toBe("my cool file");
  });

  /**
   * Frontmatter title takes priority even when filename has a date prefix.
   *
   * **Validates: Requirements 5.8, 12.2**
   */
  it("frontmatter title takes priority over filename derivation", () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 50 }).filter((s) => s.trim().length > 0),
        arbDatePrefix,
        arbStem,
        arbExt,
        (title, dateStr, stem, ext) => {
          const relativePath = `${dateStr}-${stem}${ext}`;
          const frontmatter = { title };
          const result = deriveTitle(relativePath, frontmatter);
          expect(result).toBe(title.trim());
        },
      ),
      { numRuns: 300 },
    );
  });

  /**
   * Empty or whitespace-only frontmatter.title falls back to filename derivation.
   *
   * **Validates: Requirements 5.8, 12.2**
   */
  it("falls back to filename when frontmatter.title is empty or whitespace", () => {
    fc.assert(
      fc.property(
        fc.constantFrom("", "   ", "\t", "\n"),
        arbStem,
        arbExt,
        (emptyTitle, stem, ext) => {
          const relativePath = `${stem}${ext}`;
          const frontmatter = { title: emptyTitle };
          const result = deriveTitle(relativePath, frontmatter);

          // Should derive from filename, not use the empty title
          expect(result.length).toBeGreaterThan(0);
          expect(result).not.toBe(emptyTitle);
        },
      ),
      { numRuns: 200 },
    );
  });
});

/* ------------------------------------------------------------------ */
/*  Shared arbitraries for buildContentGraph property tests           */
/* ------------------------------------------------------------------ */

const arbContentType: fc.Arbitrary<ContentType> = fc.constantFrom(
  "markdown",
  "image",
  "video",
  "audio",
);

const arbIsoDate = fc
  .record({
    year: fc.integer({ min: 1900, max: 2099 }),
    month: fc.integer({ min: 1, max: 12 }),
    day: fc.integer({ min: 1, max: 28 }),
  })
  .map(
    ({ year, month, day }) =>
      `${String(year).padStart(4, "0")}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`,
  );

const arbOptionalDate = fc.option(arbIsoDate, { nil: null });

const arbFrontmatter = fc.option(
  fc.record({
    title: fc.option(fc.string({ minLength: 0, maxLength: 30 }), { nil: undefined }),
    tags: fc.option(fc.array(fc.string({ minLength: 1, maxLength: 15 }), { maxLength: 5 }), {
      nil: undefined,
    }),
  }),
  { nil: null },
);

/** Build an array of ScannedFile with unique relative paths. */
const arbScannedFiles: fc.Arbitrary<ScannedFile[]> = fc
  .uniqueArray(
    arbStem.map((s) => s.toLowerCase()),
    { minLength: 0, maxLength: 30, comparator: (a, b) => a === b },
  )
  .chain((stems) =>
    fc.tuple(
      ...stems.map((stem) =>
        fc
          .tuple(
            arbContentType,
            arbOptionalDate,
            arbFrontmatter,
            fc.option(fc.string(), { nil: null }),
          )
          .map(([contentType, date, frontmatter, body]): ScannedFile => {
            const ext =
              contentType === "markdown"
                ? ".md"
                : contentType === "image"
                  ? ".jpg"
                  : contentType === "video"
                    ? ".mp4"
                    : ".mp3";
            return {
              absolutePath: `/tmp/test/${stem}${ext}`,
              relativePath: `${stem}${ext}`,
              contentType,
              date,
              frontmatter: frontmatter as Record<string, unknown> | null,
              body: contentType === "markdown" ? (body ?? "") : null,
            };
          }),
      ),
    ),
  );

/* ------------------------------------------------------------------ */
/*  Property 7: Graph node completeness and stats consistency         */
/* ------------------------------------------------------------------ */

describe("Content Graph — Property 7: Graph node completeness and stats consistency", () => {
  /**
   * buildContentGraph produces exactly one ContentNode per input file.
   *
   * **Validates: Requirements 5.1, 5.6**
   */
  it("produces exactly one node per input file", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        expect(Object.keys(graph.nodes).length).toBe(files.length);
      }),
      { numRuns: 200 },
    );
  });

  /**
   * stats.totalFiles equals the input length.
   *
   * **Validates: Requirements 5.1, 5.6**
   */
  it("stats.totalFiles equals input length", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        expect(graph.stats.totalFiles).toBe(files.length);
      }),
      { numRuns: 200 },
    );
  });

  /**
   * stats.datedFiles + stats.undatedFiles equals stats.totalFiles.
   *
   * **Validates: Requirements 5.1, 5.6**
   */
  it("datedFiles + undatedFiles equals totalFiles", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        expect(graph.stats.datedFiles + graph.stats.undatedFiles).toBe(graph.stats.totalFiles);
      }),
      { numRuns: 200 },
    );
  });

  /**
   * stats.byType counts match per-type totals across all nodes.
   *
   * **Validates: Requirements 5.1, 5.6**
   */
  it("byType counts match per-type node totals", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const nodes = Object.values(graph.nodes);

        for (const ct of ["markdown", "image", "video", "audio"] as ContentType[]) {
          const actual = nodes.filter((n) => n.contentType === ct).length;
          expect(graph.stats.byType[ct]).toBe(actual);
        }
      }),
      { numRuns: 200 },
    );
  });
});

/* ------------------------------------------------------------------ */
/*  Property 8: Graph partition                                       */
/* ------------------------------------------------------------------ */

describe("Content Graph — Property 8: Graph partition", () => {
  /**
   * Every node appears in exactly one of days[].nodes or undated — never both, never neither.
   *
   * **Validates: Requirements 5.2, 5.3**
   */
  it("every node is in exactly one partition: a day bucket or undated", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        const datedIds = new Set<string>();
        for (const day of graph.days) {
          for (const node of day.nodes) {
            datedIds.add(node.id);
          }
        }

        const undatedIds = new Set(graph.undated.map((n) => n.id));

        for (const id of Object.keys(graph.nodes)) {
          const inDated = datedIds.has(id);
          const inUndated = undatedIds.has(id);

          // Exactly one must be true
          expect(inDated || inUndated).toBe(true);
          expect(inDated && inUndated).toBe(false);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * Dated nodes appear in day buckets, undated nodes appear in graph.undated.
   *
   * **Validates: Requirements 5.2, 5.3**
   */
  it("dated nodes are in day buckets and undated nodes are in graph.undated", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        const datedIds = new Set<string>();
        for (const day of graph.days) {
          for (const node of day.nodes) {
            datedIds.add(node.id);
          }
        }

        for (const node of Object.values(graph.nodes)) {
          if (node.date !== null) {
            expect(datedIds.has(node.id)).toBe(true);
          } else {
            expect(graph.undated.some((u) => u.id === node.id)).toBe(true);
          }
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * No extra nodes exist in partitions that aren't in graph.nodes.
   *
   * **Validates: Requirements 5.2, 5.3**
   */
  it("no phantom nodes in partitions outside graph.nodes", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const allIds = new Set(Object.keys(graph.nodes));

        for (const day of graph.days) {
          for (const node of day.nodes) {
            expect(allIds.has(node.id)).toBe(true);
          }
        }
        for (const node of graph.undated) {
          expect(allIds.has(node.id)).toBe(true);
        }
      }),
      { numRuns: 200 },
    );
  });
});

/* ------------------------------------------------------------------ */
/*  Property 9: Day sort order                                        */
/* ------------------------------------------------------------------ */

describe("Content Graph — Property 9: Day sort order", () => {
  /**
   * For all adjacent pairs (days[i], days[i+1]), days[i].date > days[i+1].date
   * (descending chronological order).
   *
   * **Validates: Requirement 5.4**
   */
  it("days are sorted in descending chronological order", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        for (let i = 0; i < graph.days.length - 1; i++) {
          expect(graph.days[i].date > graph.days[i + 1].date).toBe(true);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * Each day bucket has a unique date string.
   *
   * **Validates: Requirement 5.4**
   */
  it("each day bucket has a unique date", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const dates = graph.days.map((d) => d.date);
        expect(new Set(dates).size).toBe(dates.length);
      }),
      { numRuns: 200 },
    );
  });
});

/* ------------------------------------------------------------------ */
/*  Property 12: Tags default to empty array                          */
/* ------------------------------------------------------------------ */

describe("Content Graph — Property 12: Tags default to empty array", () => {
  /**
   * For any ContentNode in a graph, the tags field is always an array.
   *
   * **Validates: Requirement 5.9**
   */
  it("tags is always an array for every node", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        for (const node of Object.values(graph.nodes)) {
          expect(Array.isArray(node.tags)).toBe(true);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * When frontmatter has no tags field, the tags array is empty.
   *
   * **Validates: Requirement 5.9**
   */
  it("tags is empty when frontmatter has no tags field", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        for (const node of Object.values(graph.nodes)) {
          const fm = node.frontmatter;
          if (fm === null || !("tags" in fm) || !Array.isArray(fm.tags)) {
            expect(node.tags).toEqual([]);
          }
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * When frontmatter has a tags array, the node's tags match it.
   *
   * **Validates: Requirement 5.9**
   */
  it("tags match frontmatter.tags when present as an array", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        for (const node of Object.values(graph.nodes)) {
          const fm = node.frontmatter;
          if (fm !== null && Array.isArray(fm.tags)) {
            expect(node.tags).toEqual(fm.tags);
          }
        }
      }),
      { numRuns: 200 },
    );
  });
});

import { contentGraphToLegacyIndex, getContentBody } from "./contentGraph.ts";

/* ------------------------------------------------------------------ */
/*  Property 14: Legacy adapter fidelity                              */
/* ------------------------------------------------------------------ */

describe("Content Graph — Property 14: Legacy adapter fidelity", () => {
  /**
   * contentGraphToLegacyIndex produces a ContentIndex with the same number
   * of entries as graph.nodes.
   *
   * **Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5**
   */
  it("produces the same number of entries as graph.nodes", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const index = contentGraphToLegacyIndex(graph);
        expect(Object.keys(index).length).toBe(Object.keys(graph.nodes).length);
      }),
      { numRuns: 200 },
    );
  });

  /**
   * Each entry's id, title, and tags match the source node.
   *
   * **Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5**
   */
  it("each entry's id, title, and tags match the source node", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const index = contentGraphToLegacyIndex(graph);

        for (const node of Object.values(graph.nodes)) {
          const entry = index[node.id];
          expect(entry).toBeDefined();
          expect(entry.id).toBe(node.id);
          expect(entry.title).toBe(node.title);
          expect(entry.tags).toEqual(node.tags);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * _isHeader is false for all entries.
   *
   * **Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5**
   */
  it("_isHeader is false for all entries", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const index = contentGraphToLegacyIndex(graph);

        for (const entry of Object.values(index)) {
          expect(entry._isHeader).toBe(false);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * _path equals the node's relativePath.
   *
   * **Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5**
   */
  it("_path equals relativePath for every entry", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const index = contentGraphToLegacyIndex(graph);

        for (const node of Object.values(graph.nodes)) {
          expect(index[node.id]._path).toBe(node.relativePath);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * Markdown frontmatter fields are spread into the entry.
   *
   * **Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5**
   */
  it("spreads markdown frontmatter fields into the entry", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");
        const index = contentGraphToLegacyIndex(graph);

        for (const node of Object.values(graph.nodes)) {
          if (node.frontmatter) {
            const entry = index[node.id];
            for (const [key, value] of Object.entries(node.frontmatter)) {
              // Core fields (id, title, tags, _isHeader, _path) are overridden
              // after the spread, so skip checking those
              if (["id", "title", "tags", "_isHeader", "_path"].includes(key)) {
                continue;
              }
              expect(entry[key]).toEqual(value);
            }
          }
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * getContentBody returns the node's body when it exists, null otherwise.
   *
   * **Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5**
   */
  it("getContentBody returns body for existing nodes and null for missing ones", () => {
    fc.assert(
      fc.property(arbScannedFiles, (files) => {
        const graph = buildContentGraph(files, "/tmp/test");

        for (const node of Object.values(graph.nodes)) {
          const body = getContentBody(graph, node.id);
          expect(body).toBe(node.body ?? null);
        }

        // Non-existent ID returns null
        expect(getContentBody(graph, "nonexistent-id-xyz")).toBeNull();
      }),
      { numRuns: 200 },
    );
  });
});
